version: '3'
services:

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/frontend/app
      - ./nginx/public:/frontend/public
    working_dir: /frontend/
    command: npm run build

  nginx:
    build: ./nginx/
    ports:
    - "80:80"
    volumes:
      - ./nginx/public:/data/www